### PR TITLE
Create Registry Entries

### PR DESCRIPTION
**Pull request by mikkeljohnsen**
"registry_entries": [
    	{
    		"root": "HKLM",
    		"key": "SOFTWARE\\MyApplicationName",
    		"action": "createAndRemoveOnUninstall",
    		"name": "Install_Dir",
    		"type": "string",
    		"value": "[INSTALLDIR]",
    		"key_path": "no"
    	}
    ],

### CODE REVIEW

**Comment by jpakkane** [comment]
Looks good but needs a test project using this feature.

**Comment by jpakkane** [comment]
I tested this with a simple sample and the key gets installed under `WOW6432Node` and not directly under 'SOFTWARE`. Is this intentional?

**Comment by mikkeljohnsen** [comment]
No, I assume that when making a 32bit it will put it in WOW6432Node and when making a 64bit it will put it the right place.
There don't seem to be any control over it. But I think it is the right behavior.

**Comment by jpakkane** [comment]
But this was a fully 64 bit installer, built on 64 bit Windows and installed on a 64 bit Windows. It should not have any 32 bit things in it.

**Comment by jpakkane** [comment]
The reason for this is that you must add a `Win64="yes"` to the parent `Component` entry on 64 bit platforms.

**Comment by jpakkane** [comment]
Merged manually.

**Pull request closed without merging**
